[package]
name = "hikari_math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "0.20", features = ["serde"] }

[features]
serde = ["glam/serde"]
