[package]
name = "hikari_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hikari = {path = "../"}
winit = "0.25.0"