[package]
name = "hikari-asset"
version = "0.1.0"
authors = ["atri <atrisarkar91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-gltf = "0.1.4"
thiserror = "1.0.24"
gltf = {version = "0.15.2", features = [ "import" ]}
base64 = "0.13.0"
image = {version = "0.23.14", features = ["jpeg", "png", "jpeg_rayon", "hdr"]}
rayon = "1.5.1"
glam = "0.15.0"
glfw = "0.41.0"
itertools = "0.10.0"
parking_lot = "0.11.1"

graphy = {path="../graphy"}

[dev-dependencies]
rand = "0.8.3"
