[package]
name = "hikari_3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.16.0"
hikari_render = {path = "../hikari_render"}