[package]
name = "hikari-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
profiling = {git = "https://github.com/Ax9D/profiling", branch = "master"}

[features]
profile-tracy = ["profiling/profile-with-tracy"]
profile-puffin = ["profiling/profile-with-puffin"]