[package]
name = "hikari_systems"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"

[profile.bench]
debug = true

[dev-dependencies]
rand = "0.8.4"

[features]
thread_unsafety = []